### ISSUE TITLE
error when running from object window

### ISSUE THREAD

**Issue by CShulby** [badner/lab_to_praat#13]
I ran the setup script cloned from git but I get the following error when I click to read an HTK file from the objects window:

Cannot open file “/home/cshulby/lab_to_praat/scripts/../../plugin_utils/procedures/check_filename.proc”.
Error reading file “/home/cshulby/lab_to_praat/scripts/../../plugin_utils/procedures/check_filename.proc”.
Include file “/home/cshulby/lab_to_praat/scripts/../../plugin_utils/procedures/check_filename.proc” not read.
Script “/home/cshulby/lab_to_praat/scripts/read_lab.praat” not completed.
Command "Read HTK Label file..." not executed.

**Comment by jjatria** [comment]
This is a tricky problem. Bottomline, the problem is with finding dependencies. The changes I made use some of the other existing plugins to do a number of different things. In this case, to load the [`@checkFilename`](https://gitlab.com/cpran/plugin_utils/blob/bb3176898ce1fffcfe2513743afa52303cf33dcd/procedures/check_filename.proc#L40-47) procedure, which opens a file selector when no path is given in an initial form.

Praat has no ways of cleanly finding dependencies, and the only way to import things is with the `include` directive, which takes direct paths (they cannot be interpolated, or conditionally loaded). This issue can be sidestepped as long as all scripts that include other scripts do so from a common directory structure, and use relative paths. This is explained in a little bit more detail in [one of the issues of the `cpran` plugin](https://gitlab.com/cpran/plugin_cpran/issues/10).

The "common directory structure" expects the plugins to be in the Praat preferences directory (not in your home, as in your case). And they expect to find the dependencies in the same directory (in this case, they expect to find the `utils` plugin in the preferences directory).

The solution in this case is either to a) move your plugin to [the preferences directory](http://www.fon.hum.uva.nl/praat/manual/preferences_directory.html) and b) install [the dependencies](https://github.com/badner/lab_to_praat/blob/946412f2d3a78c3cd088935b368b2be2dc7dbf91/cpran.yaml#L11-L13); or to re-write the plugin to avoid having dependencies in the first place, but I think it would be difficult to do some of the things it currently does without them.

For the record, using the CPrAN client installing this plugins dependencies is simply a matter of running `cpran deps | cpran install -` from the plugin root.

**Comment by CShulby** [comment]
so the entire lab_to_praat folder needs to be in .praat-dir/ ?

2017-03-19 8:23 GMT-03:00 José Joaquín Atria <notifications@github.com>:

**Comment by CShulby** [comment]
this did not work.  I am still confused.

2017-03-19 11:12 GMT-03:00 Christopher Shulby <chrisshulby@gmail.com>:

**Comment by CShulby** [comment]
maybe we should work on the readme?

2017-03-19 11:22 GMT-03:00 Christopher Shulby <chrisshulby@gmail.com>:

**Comment by jjatria** [comment]
I wrote about it in #10, but basically yes: the whole `lab_to_praat` needs to be under `.praat-dir` (if you are in Linux), and it needs to be renamed to something that is a plugin name (so something that starts with "plugin_", as in "plugin_lab_to_praat"). You'll _also_ need to install the dependencies, some of which have dependencies of their own. 

The full list of plugins that are needed is

* [utils](http://cpran.net/plugins/utils)
* [tap](http://cpran.net/plugins/tap)
* [selection](http://cpran.net/plugins/selection)
* [strutils](http://cpran.net/plugins/strutils)
* [varargs](http://cpran.net/plugins/varargs)
* [printf](http://cpran.net/plugins/printf)

This is all done automatically using the CPrAN client, which can be installed using Perl by running `cpanm https://gitlab.com/cpran/CPrAN.git`.

> maybe we should work on the readme? 

Sure.

**Comment by CShulby** [comment]
This is a simple solution. I can rename the whole folder to
plugin_lab_to_praat.

Am 19.03.2017 12:22 nachm. schrieb "José Joaquín Atria" <
notifications@github.com>:

**Comment by jjatria** [comment]
In that case, like I said in #10, we'll have to change it in the rest of the places where the other name ("htklabel") is being used. Basically, [in all these places](https://github.com/badner/lab_to_praat/search?utf8=%E2%9C%93&q=htklabel).

Personally, I think shorter names are better.

**Comment by CShulby** [comment]
Hmm... I agree. I think the best solution is the most automatic one.
Especially for potential users. This should not be confusing.

Am 19.03.2017 12:55 nachm. schrieb "José Joaquín Atria" <
notifications@github.com>:

**Comment by jjatria** [comment]
I know I've plugged the CPrAN client a lot already, but one of the things it does is offer a fair amount of discoverability. This is the output of `cpran list`, which shows a listing of the available plugins:

```
user@linux:~$ cpran list
Name                 Local  Remote Description                                                        
colour                      0.0.2  offers standard alternatives to Praat's native colour format       
config               0.0.3  0.0.2  Read a config file                                                 
cpran                0.2.2  0.2.2  a package manager for Praat                                        
htklabel             0.0.1         Read and write HTK/HTS label files                                 
json                 0.0.1         read and write valid JSON using Praat                              
momel-intsint                      [Not a CPrAN plugin]                                               
[... redacted for brevity ...]
vieweach             0.0.18 0.0.18 a set of customizable procedures to iterate through sets of objects
warnings                    0.0.1  procedures to enable smart warnings in Praat 
user@linux:~$ 
```

So the name is not the only thing that the users can use to find it. For the record, that string comes from [the descriptor](https://github.com/badner/lab_to_praat/blob/946412f2d3a78c3cd088935b368b2be2dc7dbf91/cpran.yaml#L18).

Here are [some other existing plugins](http://cpran.net/plugins/) if you want to know what names are out there.

**Comment by ghost** [comment]
Cannot open file “/home/badner/.praat-dir/plugin_lab_to_praat/scripts/../../plugin_utils/procedures/check_filename.proc”.

it seem that the procedures folder that is in the same folder needs to be moved to plugin_utils which I do not have.  Do I need to install something else to create it?

**Comment by CShulby** [comment]
I did some research and installed:

curl -L https://cpanmin.us | perl - --sudo App::cpanminus;
cpanm https://gitlab.com/cpran/CPrAN.git

still I do not have these guys in utils... I am still missing something

**Comment by jjatria** [comment]
I'm not sure if you've installed the dependencies I mentioned above.

If installing the client worked, try running `cpran --version`. It should report the version of the client itself, and the version of Praat it found. If it doesn't report a version for Praat, try adding Praat to your `$PATH`.

~~[Edit: I just noticed the current version dies if Praat is not in the PATH; this should be fixed soon).~~ 
[Fixed in 0.0401]

Once installed, you still need to actually install the dependencies. Try running the following:

```
cpran init
cpran update
cpran install utils tap selection strutils varargs printf
```

Let me know if after all of that you still get the same error as before.

**Comment by CShulby** [comment]
right now I have this error when I ask for the version:

Can't locate Log/Any.pm in @INC (you may need to install the Log::Any module)

This guy is not easy to install but I am fighting my way through it.

**Comment by ghost** [comment]
I have it installing now. I needed to use sudo cpanm
https://gitlab.com/cpran/CPrAN/repository/archive.tar.gz?ref=master

2017-03-19 23:13 GMT-03:00 Cshulby <notifications@github.com>:

**Comment by jjatria** [comment]
Thank you for taking the time to work through it!

FYI, when installing Perl modules using the system Perl (the one that comes with your system) you'll most likely need to use `sudo`. There are ways to avoid having to do this, and the one I prefer is using [`perlbrew`](https://perlbrew.pl/), which allows you to install different versions of Perl and switch between them (similar to how `rbenv` works). My attempt at more complete [installation instructions](http://cpran.net/clients/cpran/#installation) are on the CPrAN website. Sorry I didn't link to it before.

Then I thought that, if all you want is to install those plugins that are needed for this one to work, then you could just clone each of them using `git`:

```bash
prefdir="$HOME/.praat-dir"
pushd "${prefdir}"
for plugin in "tap" "utils" "selection" "strutils" "varargs" "printf"
  do git clone "https://gitlab.com/cpran/plugin_${plugin}"
  if [ "$(which praat)" ]
    then 
    pushd "plugin_${plugin}"
    prove --exec="$(which praat) --run --ansi --pref-dir=${prefdir}"
    popd
  else
    echo "Did not run tests"
  fi
done
popd
```

This is basically what the client is doing when you use `install` (with _a lot_ more automation and error checking in the back, but whatever).

**Comment by CShulby** [comment]
finally this worked but there is a new error:

Unknown variable:
« exitScript: "Input file """/home
Script line 1033 not performed or completed:
« exitScript: "Input file """'filename$'""" is not a valid MLF file: ", .reason$ »
Please change something in the command window “Run script: Read MLF file...”, or click Cancel in that window.

I think this is a separate issue to allow .lab files?

**Comment by jjatria** [comment]
Yeah. That's a different error. I could reproduce it here. #15 should fix it.

The error comes up when it tries to open a file as an MLF and the input is somehow not valid (eg. missing the header).

**Comment by jjatria** [comment]
By the way: `.lab` files and `.mlf` files are not the same, and are not treated as the same by these scripts. If you try to open a `.lab` file with `Read HTK Master Label File...` you'll get an error again. The same goes if you try to open an `.mlf` file with `Read HTK label file...`.

**Comment by CShulby** [comment]
this still does not work and is very confusing.

**Comment by CShulby** [comment]
ok I was able to open the file after I installed each plugin manually by cloning into them 

* [tap](https://gitlab.com/cpran/plugin_tap)
* [utils](https://gitlab.com/cpran/plugin_utils)
* [varargs](https://gitlab.com/cpran/plugin_varargs)
* [printf](https://gitlab.com/cpran/plugin_printf)
* [selection](https://gitlab.com/cpran/plugin_selection)
* [strutils](https://gitlab.com/cpran/plugin_strutils)

**Comment by CShulby** [comment]
this should be done automatically shouldn't it?

**Comment by jjatria** [comment]
It should.

It would be easier to understand where the problem lies if you gave me a little more information.

* What do you think is confusing?
* When you say it doesn't work, does it give you the same error message? Or a different one?
* What is the file you are trying to open? What command are you using to open it?
* What problems did you run into when trying to install the dependencies automatically with the commands I gave you?

**Comment by CShulby** [comment]
the problem is the dependencies.

It was confusing because all of the dependencies were on my machine but were missing files as in this error.

when I installed each dependency individually, it worked.  I am not sure my it didn't work before.

**Comment by CShulby** [comment]
It seems that the dependencies do not force install when the folder already exists.  I think this is the problem.  I had a bad install (I am guessing) on my machine.

Removing them and installing them 1 by 1 worked.

**Comment by CShulby** [comment]
now it opens the .lab with the audio and everything is great! 

The issue is forcing this to install automatically

**Comment by jjatria** [comment]
I'm glad it worked!

There is an option for the `install` command that does what you want: `--reinstall`. That ignores the fact that a plugin is already there, and replaces it with the requested one.

The `--force` option is already taken to ignore failing tests.

You can see all the options and a brief explanation of what they do with `cpran help install`.

I guess you can close this issue now, and open a new one if something else comes up.

**Comment by CShulby** [comment]
ok.  would you mind including this in the readme if someone has issues?  I am going to include some information about the use of the plugin.
