### ISSUE TITLE
creates multiple plugins

### ISSUE THREAD

**Issue by CShulby** [badner/lab_to_praat#14]
when the setup is run the buttons are repeated

**Comment by jjatria** [comment]
The [`setup.praat`](https://github.com/badner/lab_to_praat/blob/master/setup.praat) file only has those commands once, so if they are running more than once, it must be because the script is running more than once, which means the plugin is being loaded more than once. 

You don't have it installed more than once under different names, or something like that, do you? What plugins are installed in the preferences directory?

**Comment by CShulby** [comment]
ok setup was run twice... is there a way to check if it has been run?  that
would make things smoother.

2017-03-19 8:26 GMT-03:00 José Joaquín Atria <notifications@github.com>:

**Comment by jjatria** [comment]
Sadly, no straightforward way to do it, no. You just need to make sure the plugin is only there once. 

Was it there more than once in your setup?

**Comment by CShulby** [comment]
I may have had the old plugins as well. Can they be removed? Even manually?

Am 19.03.2017 12:25 nachm. schrieb "José Joaquín Atria" <
notifications@github.com>:

**Comment by jjatria** [comment]
Sure. Just go to the preferences directory and delete them. Anything with a name that starts with "plugin_" is a plugin. Anything else is not. 

You can also safely delete the entire preferences directory itself, and Praat will recreate it with defaults when next started. This will destroy any saved preferences, but if you haven't changed anything, that is completely safe to do.

**Comment by CShulby** [comment]
Cool. I will test this later.

Am 19.03.2017 12:52 nachm. schrieb "José Joaquín Atria" <
notifications@github.com>:

**Comment by jjatria** [comment]
Any updates on this?

**Comment by CShulby** [comment]
this is resolved
